import { expect, test } from '@playwright/test'
test('public introduction and signup save name and icon in registration metadata',async({page})=>{
 let registration: Record<string,unknown>|null=null
 await page.route('https://example.supabase.co/**',async route=>{
  const url=new URL(route.request().url()),method=route.request().method()
  if(method==='OPTIONS')return route.fulfill({status:204})
  if(url.pathname.endsWith('/signup')){registration=route.request().postDataJSON();return route.fulfill({contentType:'application/json',body:JSON.stringify({user:{id:'new-user',email:'new@example.com'},session:null})})}
  return route.fulfill({contentType:'application/json',body:JSON.stringify([])})
 })
 await page.goto('/')
 await expect(page.getByRole('heading',{name:/その記録、\s*もっと活かせる/})).toBeVisible()
 await page.getByRole('link',{name:'アカウントを作って始める'}).click()
 await page.getByLabel('名前',{exact:true}).fill('新人')
 await page.getByRole('button',{name:'バーベル',exact:true}).click()
 await page.getByLabel('全体ランキングに参加する').check()
 await page.getByLabel('メールアドレス').fill('new@example.com')
 await page.getByLabel('パスワード').fill('strong-password-123')
 await page.getByRole('button',{name:'アカウントを作成',exact:true}).click()
 await expect(page.getByRole('status')).toContainText('確認メール')
 expect(registration).toMatchObject({data:{display_name:'新人',profile_icon:'barbell',global_ranking:true}})
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true)
})

test('landing showcases graphs, AI export and personal rankings on phones and desktop', async ({ page }) => {
  const errors: string[] = []
  const mutations: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  page.on('console', message => { if (message.type() === 'error') errors.push(message.text()) })
  await page.route('https://example.supabase.co/**', route => {
    const method = route.request().method()
    if (!['GET', 'OPTIONS'].includes(method)) mutations.push(method)
    return method === 'OPTIONS' ? route.fulfill({ status: 204 }) : route.fulfill({ contentType: 'application/json', body: '[]' })
  })
  await page.goto('/')
  await expect(page.getByRole('heading', { level: 1, name: /その記録、\s*もっと活かせる/ })).toBeVisible()
  const preview = page.getByRole('group', { name: '画面プレビュー切り替え' })
  for (const width of [320, 375, 390, 1280]) {
    await page.setViewportSize({ width, height: width === 1280 ? 900 : 844 })
    await preview.getByRole('button', { name: 'グラフ', exact: true }).click()
    await expect(page.getByRole('region', { name: '成長グラフのサンプル' })).toBeVisible()
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
    await page.evaluate(() => window.scrollTo(0, 0))
    await page.screenshot({ path: 'test-results/landing-graph-' + width + '.png', fullPage: true, animations: 'disabled' })
    await page.screenshot({ path: 'test-results/landing-hero-' + width + '.png', animations: 'disabled' })
    await preview.getByRole('button', { name: 'AI相談', exact: true }).click()
    const exported = page.getByRole('region', { name: 'エクスポートのサンプル' })
    await expect(exported).toContainText('Markdown')
    const example = exported.getByRole('button', { name: /AIへの相談例を見る|相談の例を閉じる/ })
    await expect(example).toHaveAttribute('aria-expanded', 'false')
    await example.click()
    await expect(example).toHaveAttribute('aria-expanded', 'true')
    await expect(exported).toContainText('次回の重量と回数の目安')
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
    await page.screenshot({ path: 'test-results/landing-ai-' + width + '.png', animations: 'disabled' })
    await preview.getByRole('button', { name: 'ランキング', exact: true }).click()
    const ranking = page.getByRole('region', { name: 'ランキングのサンプル' })
    await expect(ranking).toContainText('いつものジム仲間')
    await expect(ranking).toContainText('450kg')
    await ranking.getByRole('button', { name: 'DOTS', exact: true }).click()
    await expect(ranking).toContainText('340.5')
    await expect(ranking).not.toContainText('450kg')
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
    for (const button of await preview.getByRole('button').all()) {
      expect((await button.boundingBox())!.height).toBeGreaterThanOrEqual(56)
    }
  }
  // People switching from another app: what to do, and an honest note about past records.
  const switching = page.getByRole('region', { name: '乗り換えは、1分で。' })
  await expect(switching.getByRole('listitem')).toHaveText([/アカウントを作る/, /BIG3のベストを入れる/, /今日から推定1RM・合計・ランキング/])
  await expect(switching).toContainText('今のアプリの記録を自動で取り込む機能はありません。')
  await expect(page.getByText('ほかのアプリからの乗り換えも、1分で')).toBeVisible()
  const moving = page.locator('details').filter({ has: page.locator('summary', { hasText: '今使っているアプリの記録は移せますか？' }) })
  await moving.locator('summary').click()
  await expect(moving).toContainText('BIG3のベストを入れれば')
  const faq = page.locator('details').filter({ has: page.locator('summary', { hasText: 'AIにはどうやって相談しますか？' }) })
  await expect(faq).not.toHaveAttribute('open')
  await faq.locator('summary').click()
  await expect(faq).toHaveAttribute('open')
  await expect(faq).toContainText('相談はGlogの外で行います')
  await page.getByRole('link', { name: 'Glogを始める', exact: true }).click()
  await expect(page).toHaveURL(/\/signup$/)
  await expect(page.getByRole('heading', { name: 'プロフィールを作って始める' })).toBeVisible()
  await page.goto('/')
  await page.getByRole('link', { name: 'ログイン', exact: true }).click()
  await expect(page).toHaveURL(/\/login$/)
  expect(mutations).toEqual([])
  expect(errors).toEqual([])
})
