import { beforeEach, expect, it, vi } from 'vitest'
import { act, render, screen, waitFor } from '@testing-library/react'
import userEvent from '@testing-library/user-event'
import { HealthSyncPanel } from './HealthSyncPanel'
const { issue, status, revoke } = vi.hoisted(() => ({ issue:vi.fn(), status:vi.fn(), revoke:vi.fn() }))
const shortcut = vi.hoisted(() => ({ release: null as { importUrl: string; verifiedOn: string } | null }))
vi.mock('./healthSyncShortcut', () => ({ get healthSyncShortcut() { return shortcut.release } }))
vi.mock('./healthSyncQueries', () => ({ issueHealthSyncToken:issue, fetchHealthSyncStatus:status, revokeHealthSyncToken:revoke,
  healthSyncEndpoint:'https://example.supabase.co/functions/v1/body-metrics' }))
const time='2026-10-01T00:00:00Z', token='a'.repeat(64)
const disconnected={ enabled:false, issued_at:null, last_synced_at:null, last_synced_count:null }
beforeEach(() => {
  shortcut.release = null
  Element.prototype.scrollIntoView = vi.fn()
  vi.clearAllMocks(); status.mockResolvedValue(disconnected)
  issue.mockResolvedValue({token, issued_at:time}); revoke.mockResolvedValue(undefined)
})

it('keeps installation unavailable until a credential-free template is verified', async () => {
  render(<HealthSyncPanel userId="u1" refreshVersion={0}/>); await open()
  expect(screen.getByText(/^簡単追加は準備中です/)).toBeInTheDocument()
  expect(screen.queryByRole('link', {name:'同期ショートカットを追加'})).not.toBeInTheDocument()
  expect(screen.getByRole('button', {name:'同期結果を確認'})).toBeDisabled()
  await userEvent.click(screen.getByRole('button', {name:'手動設定の手順を見る'}))
  expect(screen.getByLabelText('送信先URL')).toBeVisible()
  expect(screen.getByRole('link', {name:'iPhoneでショートカットを開く'})).toHaveAttribute('href', 'shortcuts://')
})

it('opens a verified shared template without embedding a personal credential', async () => {
  const importUrl = 'https://www.icloud.com/shortcuts/' + 'c'.repeat(32)
  shortcut.release = { importUrl, verifiedOn: '2026-10-03' }
  render(<HealthSyncPanel userId="u1" refreshVersion={0}/>); await open()
  await userEvent.click(screen.getByRole('button', {name:'連携キーを発行'}))
  await screen.findByLabelText('新しい連携キー')
  const install = screen.getByRole('link', {name:'同期ショートカットを追加'})
  expect(install).toHaveAttribute('href', importUrl)
  expect(install.getAttribute('href')).not.toContain(token)
  expect(screen.queryByRole('button', {name:'手動設定の手順を見る'})).not.toBeInTheDocument()
  expect(screen.getByText('初回同期待ち')).toBeInTheDocument()
  expect(screen.queryByText('連携中')).not.toBeInTheDocument()
})

it('does not offer an install URL that contains a token, query, or a different host', async () => {
  shortcut.release = { importUrl: 'https://www.icloud.com/shortcuts/' + 'c'.repeat(32) + '?token=' + token, verifiedOn: '2026-10-03' }
  const view = render(<HealthSyncPanel userId="u1" refreshVersion={0}/>); await open()
  expect(screen.queryByRole('link', {name:'同期ショートカットを追加'})).not.toBeInTheDocument()
  view.unmount()
  shortcut.release = { importUrl: 'https://example.com/shortcuts/' + 'c'.repeat(32), verifiedOn: '2026-10-03' }
  render(<HealthSyncPanel userId="u1" refreshVersion={0}/>); await open()
  expect(screen.queryByRole('link', {name:'同期ショートカットを追加'})).not.toBeInTheDocument()
})

it('checks the shared records reload and waits for an actual successful sync', async () => {
  const onReload = vi.fn()
  const view = render(<HealthSyncPanel userId="u1" refreshVersion={0} onReload={onReload}/>); await open()
  await userEvent.click(screen.getByRole('button', {name:'連携キーを発行'}))
  await screen.findByText('初回同期待ち')
  await userEvent.click(screen.getByRole('button', {name:'同期結果を確認'}))
  expect(onReload).toHaveBeenCalledOnce()
  expect(screen.queryByText('連携中')).not.toBeInTheDocument()
  status.mockResolvedValue({...disconnected, enabled:true, issued_at:time, last_synced_at:time, last_synced_count:1})
  view.rerender(<HealthSyncPanel userId="u1" refreshVersion={1} onReload={onReload}/>)
  await screen.findByText('連携中')
  expect(screen.getByText(/書き込み 1件/)).toBeInTheDocument()
})

it('requires a new sync after rotation while retaining previous sync history', async () => {
  status.mockResolvedValue({...disconnected, enabled:true, issued_at:time, last_synced_at:time, last_synced_count:2})
  issue.mockResolvedValue({token, issued_at:'2026-10-02T00:00:00Z'})
  render(<HealthSyncPanel userId="u1" refreshVersion={0}/>)
  await userEvent.click(screen.getByRole('button', {name:'ヘルスケア連携'}))
  await screen.findByText('連携中')
  await userEvent.click(screen.getByRole('button', {name:'連携キーを再発行'}))
  await userEvent.click(screen.getByRole('button', {name:'再発行する'}))
  await screen.findByText('初回同期待ち')
  expect(screen.getByText(/書き込み 2件/)).toBeInTheDocument()
})
const manage = async () => {
  const summary = screen.getByText('連携キーの管理')
  if (!(summary.closest('details') as HTMLDetailsElement).open) await userEvent.click(summary)
}
const open = async () => {
  await userEvent.click(screen.getByRole('button',{name:'ヘルスケア連携'}))
  await screen.findByText('未接続')
}
it('starts closed without RPC and displays a new token only until unmount', async () => {
  const view=render(<HealthSyncPanel userId="u1" refreshVersion={0}/>)
  expect(status).not.toHaveBeenCalled(); await open()
  await userEvent.click(screen.getByRole('button',{name:'連携キーを発行'}))
  expect(await screen.findByLabelText('新しい連携キー')).toHaveValue(token)
  expect(screen.getByText(/この画面を離れると/)).toBeInTheDocument()
  view.unmount(); status.mockResolvedValue({...disconnected, enabled:true, issued_at:time})
  render(<HealthSyncPanel userId="u1" refreshVersion={0}/>)
  await userEvent.click(screen.getByRole('button',{name:'ヘルスケア連携'}))
  expect(await screen.findByText('初回同期待ち')).toBeInTheDocument()
  expect(screen.queryByLabelText('新しい連携キー')).not.toBeInTheDocument()
})
it('confirms rotation/revocation effects and retains last successful write count', async () => {
  status.mockResolvedValue({...disconnected, enabled:true, issued_at:time, last_synced_at:time, last_synced_count:2})
  render(<HealthSyncPanel userId="u1" refreshVersion={0}/>)
  await userEvent.click(screen.getByRole('button',{name:'ヘルスケア連携'}))
  await screen.findByText('連携中')
  expect(screen.getByText(/書き込み 2件/)).toBeInTheDocument()
  await manage(); await userEvent.click(screen.getByRole('button',{name:'連携キーを再発行'}))
  expect(screen.getByRole('alertdialog')).toHaveTextContent('以前の連携キー')
  expect(issue).not.toHaveBeenCalled()
  await userEvent.click(screen.getByRole('button',{name:'キャンセル'}))
  await manage(); await userEvent.click(screen.getByRole('button',{name:'連携キーを再発行'}))
  await userEvent.click(screen.getByRole('button',{name:'再発行する'}))
  await screen.findByLabelText('新しい連携キー')
  await manage(); await userEvent.click(screen.getByRole('button',{name:'連携を失効'}))
  expect(screen.getByRole('alertdialog')).toHaveTextContent('同期できなく')
  expect(revoke).not.toHaveBeenCalled()
  await userEvent.click(screen.getByRole('button',{name:'失効する'}))
  await screen.findByText('未接続')
  expect(revoke).toHaveBeenCalledOnce()
  expect(screen.queryByLabelText('新しい連携キー')).not.toBeInTheDocument()
  expect(screen.getByText(/書き込み 2件/)).toBeInTheDocument()
})
it('shows status failure and retry rather than a disconnected claim', async () => {
  status.mockRejectedValueOnce(new TypeError('fetch failed')).mockResolvedValue(disconnected)
  render(<HealthSyncPanel userId="u1" refreshVersion={0}/>)
  await userEvent.click(screen.getByRole('button',{name:'ヘルスケア連携'}))
  expect(await screen.findByRole('alert')).toHaveTextContent('通信')
  expect(screen.queryByText('未接続')).not.toBeInTheDocument()
  expect(screen.queryByRole('button',{name:'連携キーを発行'})).not.toBeInTheDocument()
  await userEvent.click(screen.getByRole('button',{name:'接続状態を再試行'}))
  await screen.findByText('未接続')
})
it('retries failed issuance and supports manual copy when clipboard fails', async () => {
  Object.defineProperty(navigator,'clipboard',{configurable:true,value:{writeText:vi.fn().mockRejectedValue(new Error('denied'))}})
  issue.mockRejectedValueOnce(new Error('failed')).mockResolvedValue({token,issued_at:time})
  render(<HealthSyncPanel userId="u1" refreshVersion={0}/>); await open()
  await userEvent.click(screen.getByRole('button',{name:'連携キーを発行'}))
  await screen.findByRole('alert')
  await userEvent.click(screen.getByRole('button',{name:'操作を再試行'}))
  const input=await screen.findByLabelText('新しい連携キー')
  await userEvent.click(screen.getByRole('button',{name:'連携キーをコピー'}))
  expect(await screen.findByText(/長押しして/)).toBeInTheDocument()
  await userEvent.click(input)
  expect((input as HTMLTextAreaElement).selectionEnd).toBe(64)
  await userEvent.click(screen.getByRole('button',{name:'手動設定の手順を見る'}))
  await userEvent.click(screen.getByRole('button',{name:'送信先URLをコピー'}))
  expect(screen.getByLabelText('送信先URL')).toHaveValue('https://example.supabase.co/functions/v1/body-metrics')
})
it('clears raw token immediately on user change and logout', async () => {
  const view=render(<HealthSyncPanel userId="u1" refreshVersion={0}/>); await open()
  await userEvent.click(screen.getByRole('button',{name:'連携キーを発行'})); await screen.findByLabelText('新しい連携キー')
  view.rerender(<HealthSyncPanel userId="u2" refreshVersion={0}/>)
  expect(screen.queryByLabelText('新しい連携キー')).not.toBeInTheDocument()
  view.rerender(<HealthSyncPanel userId={null} refreshVersion={0}/>)
  expect(screen.queryByLabelText('新しい連携キー')).not.toBeInTheDocument()
})
it('ignores an issuance that finishes after its owner leaves', async () => {
  let resolve!: (data:unknown) => void
  issue.mockReturnValue(new Promise((r) => {resolve=r}))
  const view=render(<HealthSyncPanel userId="u1" refreshVersion={0}/>); await open()
  await userEvent.click(screen.getByRole('button',{name:'連携キーを発行'}))
  view.rerender(<HealthSyncPanel userId="u2" refreshVersion={0}/>)
  await act(async () => resolve({token,issued_at:time}))
  expect(screen.queryByLabelText('新しい連携キー')).not.toBeInTheDocument()
})
it('refreshes the last-sync state after the shared records reload and exposes the complete guide', async () => {
  const view=render(<HealthSyncPanel userId="u1" refreshVersion={0}/>); await open()
  status.mockResolvedValue({...disconnected,enabled:true,last_synced_at:time,last_synced_count:0})
  view.rerender(<HealthSyncPanel userId="u1" refreshVersion={1}/>)
  await waitFor(() => expect(screen.getByText(/書き込み 0件/)).toBeInTheDocument())
  await userEvent.click(screen.getByText('iPhoneショートカットの設定手順'))
  expect(screen.getByTestId('health-sync-guide')).toHaveTextContent('yyyy-MM-dd')
  expect(screen.getByTestId('health-sync-guide')).toHaveTextContent('256KiB')
})

it('clears the previous raw token before a rotation whose response fails', async () => {
  render(<HealthSyncPanel userId="u1" refreshVersion={0}/>); await open()
  await userEvent.click(screen.getByRole('button',{name:'連携キーを発行'})); await screen.findByLabelText('新しい連携キー')
  issue.mockRejectedValue(new Error('response lost after server rotated'))
  await manage(); await userEvent.click(screen.getByRole('button',{name:'連携キーを再発行'}))
  await userEvent.click(screen.getByRole('button',{name:'再発行する'}))
  await screen.findByRole('alert')
  expect(screen.queryByLabelText('新しい連携キー')).not.toBeInTheDocument()
})
it('discards late status and revoke results after the owner changes', async () => {
  let finishStatus!: (data:unknown) => void
  status.mockReturnValue(new Promise((r) => {finishStatus=r}))
  const view=render(<HealthSyncPanel userId="u1" refreshVersion={0}/>)
  await userEvent.click(screen.getByRole('button',{name:'ヘルスケア連携'}))
  view.rerender(<HealthSyncPanel userId="u2" refreshVersion={0}/>)
  await act(async () => finishStatus({...disconnected,enabled:true,last_synced_count:9,last_synced_at:time}))
  expect(screen.queryByText(/書き込み 9件/)).not.toBeInTheDocument()
  status.mockResolvedValue({...disconnected,enabled:true,issued_at:time})
  await userEvent.click(screen.getByRole('button',{name:'ヘルスケア連携'}))
  await screen.findByText('初回同期待ち')
  let finishRevoke!: () => void
  revoke.mockReturnValue(new Promise<void>((r) => {finishRevoke=r}))
  await manage(); await userEvent.click(screen.getByRole('button',{name:'連携を失効'}))
  await userEvent.click(screen.getByRole('button',{name:'失効する'}))
  view.rerender(<HealthSyncPanel userId="u3" refreshVersion={0}/>)
  await act(async () => finishRevoke())
  expect(screen.queryByText('未接続')).not.toBeInTheDocument()
})
